---
name: Validate YAML

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install yamllint
        run: pip install yamllint
      - name: Validate YAML files
        run: yamllint Codertext.yaml.txt ultimate_coder/resources/knowledgebase.yaml
